/* 004133f5 FUN_004133f5 */

/* WARNING: Function: __security_check_cookie replaced with injection: security_check_cookie */

undefined4 __thiscall
FUN_004133f5(void *this,undefined4 param_1,int *param_2,uint *param_3,undefined4 param_4,
            int *param_5)

{
  undefined4 uVar1;
  char *pcVar2;
  int iVar3;
  uint uVar4;
  bool bVar5;
  longlong lVar6;
  uint unaff_retaddr;
  int local_188;
  uint local_184;
  undefined8 local_180;
  int local_178;
  undefined4 local_174;
  undefined4 local_170;
  char local_168 [24];
  FILE *local_150;
  wchar_t local_14c [8];
  tm *local_13c;
  wchar_t local_138 [8];
  uint local_128;
  uint local_124;
  uint local_120;
  uint local_11c [66];
  uint local_14;
  int local_10;
  undefined8 local_c;
  
  local_14 = DAT_00451a00 ^ unaff_retaddr;
  iVar3 = param_5[1];
  if (iVar3 == 0x408) {
    local_128 = 0x10;
    local_120 = 9;
  }
  else if (iVar3 == 0x419) {
    local_128 = 8;
    local_120 = 0xc;
  }
  else if (iVar3 == 0x41a) {
    local_128 = 0x20;
    local_120 = 6;
  }
  else if (iVar3 == 0x41b) {
    local_128 = 0x40;
    local_120 = 4;
  }
  else if (iVar3 == 0x41c) {
    local_128 = param_5[2];
    local_120 = 0x46 / (uint)param_5[2];
  }
  local_150 = (FILE *)FUN_0043e6f2((char *)param_3,"wt");
  if (local_150 == (FILE *)0x0) {
    uVar1 = 0x2b0006;
  }
  else {
    FID_conflict__fwprintf(local_150,(wchar_t *)"/*\n %s\n",param_4);
    FID_conflict___time32((__time32_t *)&local_180);
    local_13c = _localtime(&local_180);
    pcVar2 = FUN_0043fe7d(&local_13c->tm_sec);
    FID_conflict__fwprintf(local_150,(wchar_t *)" Generated by Logic Friday on %s*/\n\n",pcVar2);
    for (local_184 = 0; local_184 < (uint)param_2[0x32]; local_184 = local_184 + 1) {
      FUN_0043ed39(local_168,(byte *)"lu_%s");
      if (*param_5 == 0x423) {
        FID_conflict__fwprintf(local_150,(wchar_t *)"int %s( unsigned int nTerm );\n",local_168);
      }
      else {
        local_10 = 0;
        iVar3 = FID_conflict__fwprintf(local_150,(wchar_t *)"int %s( ",local_168);
        local_10 = local_10 + iVar3;
        for (local_124 = 0; (int)local_124 < param_2[0x31]; local_124 = local_124 + 1) {
          if ((int)local_124 < param_2[0x31] + -1) {
            iVar3 = FID_conflict__fwprintf
                              (local_150,(wchar_t *)"int %s, ",(int)param_2 + local_124 * 9 + 0x160)
            ;
            local_10 = local_10 + iVar3;
            if (0x41 < local_10) {
              local_10 = FID_conflict__fwprintf(local_150,L"ऊ");
            }
          }
          else {
            FID_conflict__fwprintf
                      (local_150,(wchar_t *)"int %s );\n",(int)param_2 + local_124 * 9 + 0x160);
          }
        }
      }
    }
    FID_conflict__fwprintf(local_150,L"\n");
    if (DAT_00452ef4 != 0) {
      FUN_00413c2e(this,local_150,(int)param_2,param_5);
    }
    for (local_184 = 0; local_184 < (uint)param_2[0x32]; local_184 = local_184 + 1) {
      FUN_0043ed39(local_168,(byte *)"lu_%s");
      if (*param_5 == 0x423) {
        FID_conflict__fwprintf(local_150,(wchar_t *)"int %s( unsigned int nTerm )\n{\n",local_168);
      }
      else {
        local_10 = 0;
        iVar3 = FID_conflict__fwprintf(local_150,(wchar_t *)"int %s( ",local_168);
        local_10 = local_10 + iVar3;
        for (local_124 = 0; (int)local_124 < param_2[0x31]; local_124 = local_124 + 1) {
          if ((int)local_124 < param_2[0x31] + -1) {
            iVar3 = FID_conflict__fwprintf
                              (local_150,(wchar_t *)"int %s, ",(int)param_2 + local_124 * 9 + 0x160)
            ;
            local_10 = local_10 + iVar3;
            if (0x41 < local_10) {
              local_10 = FID_conflict__fwprintf(local_150,L"ऊ");
            }
          }
          else {
            FID_conflict__fwprintf
                      (local_150,(wchar_t *)"int %s )\n{\n",(int)param_2 + local_124 * 9 + 0x160);
          }
        }
      }
      FID_conflict__fwprintf(local_150,(wchar_t *)"\tconst unsigned int nOutAry[] =\n\t{");
      if (local_128 < 0x21) {
        FUN_0043ed39((char *)local_138,(byte *)"%s%d%s");
        FUN_0043ed39((char *)local_14c,(byte *)"%s%d%s");
      }
      else {
        FUN_0043ed39((char *)local_138,(byte *)"%s%d%s");
        FUN_0043ed39((char *)local_14c,(byte *)"%s%d%s");
      }
      local_188 = 0;
      local_180._4_4_ = 1;
      local_178 = *param_2;
      while (local_188 < local_178) {
        lVar6 = 0;
        local_124 = local_128;
        do {
          local_124 = local_124 - 1;
          if ((int)local_124 < 0) break;
          if (*(int *)(param_2[local_184 + 0x21] + local_188 * 4) != 0) {
            local_174 = 1;
            local_170 = 0;
            local_c = lVar6;
            lVar6 = __allshl((byte)local_124,0);
            lVar6 = lVar6 + local_c;
          }
          local_188 = local_188 + 1;
        } while (local_188 < local_178);
        local_c._4_4_ = (undefined4)((ulonglong)lVar6 >> 0x20);
        local_c._0_4_ = (undefined4)lVar6;
        if (local_188 < local_178 + -1) {
          FID_conflict__fwprintf(local_150,local_138,(undefined4)local_c,local_c._4_4_);
          local_c = lVar6;
          uVar4 = local_180._4_4_ + 1;
          bVar5 = local_120 <= local_180._4_4_;
          local_180._4_4_ = uVar4;
          if (bVar5) {
            FID_conflict__fwprintf(local_150,L"ऊ 㙉場㭽ਊ");
            local_180._4_4_ = 1;
          }
        }
        else {
          FID_conflict__fwprintf(local_150,local_14c,(undefined4)local_c,local_c._4_4_);
          local_c = lVar6;
        }
        local_c._0_4_ = 0;
        local_c._4_4_ = 0;
      }
      if (*param_5 == 0x420) {
        FID_conflict__fwprintf(local_150,(wchar_t *)"\tunsigned int nTerm=0, nX, nBit;\n\n");
        for (local_124 = 0; (int)local_124 < param_2[0x31]; local_124 = local_124 + 1) {
          if (local_124 == param_2[0x31] - 1U) {
            FID_conflict__fwprintf
                      (local_150,(wchar_t *)"\tif( %s ) nTerm |= 1;\n",
                       (int)param_2 + local_124 * 9 + 0x160,(param_2[0x31] + -1) - local_124);
          }
          else {
            FID_conflict__fwprintf
                      (local_150,(wchar_t *)"\tif( %s ) nTerm |= 1<<%d;\n",
                       (int)param_2 + local_124 * 9 + 0x160,(param_2[0x31] + -1) - local_124);
          }
        }
      }
      else {
        FID_conflict__fwprintf(local_150,(wchar_t *)"\tunsigned int nX, nBit;\n\n");
      }
      FID_conflict__fwprintf(local_150,(wchar_t *)"\tnX = nTerm / %d;\n",local_128);
      FID_conflict__fwprintf
                (local_150,(wchar_t *)"\tnBit = %d - nTerm %% %d;\n",local_128 - 1,local_128);
      FID_conflict__fwprintf
                (local_150,
                 (wchar_t *)"\tif( nOutAry[nX] & 1<<nBit )\n\t\treturn 1;\n\telse\n\t\treturn 0;\n}"
                );
      FID_conflict__fwprintf(local_150,L"ਊ");
    }
    _fclose(local_150);
    GetWindowsDirectoryA((LPSTR)local_11c,0x104);
    iVar3 = __stricmp((char *)local_11c,"c:\\");
    if (iVar3 != 0) {
      FUN_0043ebe0(local_11c,(uint *)&DAT_0044bf60);
    }
    FUN_0043ebe0(local_11c,(uint *)"notepad ");
    FUN_0043ebe0(local_11c,param_3);
    WinExec((LPCSTR)local_11c,5);
    uVar1 = 0;
  }
  return uVar1;
}
