[package]
name = "logicfriday1_espresso"
version = "0.1.0"
edition = "2024"
build = "build.rs"
autobins = false

[lib]
crate-type = ["cdylib", "rlib"]

[build-dependencies]
csbindgen = "1.9.8"

[profile.dev]
opt-level = 0
incremental = true
codegen-units = 256
lto = false
debug = 1

[profile.release]
opt-level = "z"
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "symbols"
debug = false
