using LogicFriday1.Models;
using LogicFriday1.Services;
using Shouldly;
using Xunit;

namespace LogicFriday1.Tests;

public sealed class LookupFunctionGeneratorTests
{
    public static IEnumerable<object[]> LanguageCases
    {
        get
        {
            yield return
            [
                LookupFunctionLanguage.Vhdl,
                ".vhd",
                "constant LU_F : lookup_table := ('0', '1', '0', '1');",
                "F <= LU_F(n_term);"
            ];
            yield return
            [
                LookupFunctionLanguage.Verilog,
                ".v",
                "2'd2: lookup_value = 2'b10;",
                "assign G = lookup_value[1];"
            ];
            yield return
            [
                LookupFunctionLanguage.C,
                ".c",
                "static const unsigned char LU_F[] = { 0, 1, 0, 1 };",
                "int lu_F(unsigned int nTerm)"
            ];
            yield return
            [
                LookupFunctionLanguage.Rust,
                ".rs",
                "const LU_F: [u8; 4] = [0, 1, 0, 1];",
                "pub fn lu_F(n_term: usize) -> bool"
            ];
            yield return
            [
                LookupFunctionLanguage.CSharp,
                ".cs",
                "private static readonly byte[] LU_F = [0, 1, 0, 1];",
                "public static bool lu_F(int nTerm)"
            ];
            yield return
            [
                LookupFunctionLanguage.Java,
                ".java",
                "private static final byte[] LU_F = new byte[] { 0, 1, 0, 1 };",
                "public static boolean lu_F(int nTerm)"
            ];
            yield return
            [
                LookupFunctionLanguage.Python,
                ".py",
                "LU_F = [0, 1, 0, 1]",
                "def lu_F(n_term: int) -> bool:"
            ];
            yield return
            [
                LookupFunctionLanguage.JavaScript,
                ".js",
                "const LU_F = [0, 1, 0, 1];",
                "export function lu_F(nTerm)"
            ];
            yield return
            [
                LookupFunctionLanguage.Go,
                ".go",
                "var LU_F = []byte{ 0, 1, 0, 1 }",
                "func lu_F(nTerm int) bool"
            ];
        }
    }

    [Theory]
    [MemberData(nameof(LanguageCases))]
    public void Generate_EmitsLookupSourceForLanguage(
        LookupFunctionLanguage language,
        string expectedExtension,
        string expectedTableSnippet,
        string expectedFunctionSnippet)
    {
        var result = LookupFunctionGenerator.Generate(CreateSampleFunction(), language);

        result.ShouldSatisfyAllConditions(
            () => result.FileExtension.ShouldBe(expectedExtension),
            () => result.SourceCode.ShouldContain(expectedTableSnippet),
            () => result.SourceCode.ShouldContain(expectedFunctionSnippet),
            () => result.SourceCode.ShouldContain("Outputs: F, G"));
    }

    [Fact]
    public void Generate_SanitizesDuplicateOutputNames()
    {
        var logicFunction = new TruthTableLogicFunction(
            ["A"],
            ["F.Out", "F_Out"],
            [
                ["0", "1"],
                ["1", "0"]
            ],
            "F.Out = A; F_Out = A';");

        var result = LookupFunctionGenerator.Generate(logicFunction, LookupFunctionLanguage.CSharp);

        result.SourceCode.ShouldSatisfyAllConditions(
            sourceCode => sourceCode.ShouldContain("private static readonly byte[] LU_F_OUT = [0, 1];"),
            sourceCode => sourceCode.ShouldContain("private static readonly byte[] LU_F_OUT_2 = [1, 0];"),
            sourceCode => sourceCode.ShouldContain("public static bool lu_F_Out_2(int nTerm)"));
    }

    [Fact]
    public void Generate_UsesLanguageSpecificHeaderComments()
    {
        var vhdl = LookupFunctionGenerator.Generate(CreateSampleFunction(), LookupFunctionLanguage.Vhdl);
        var python = LookupFunctionGenerator.Generate(CreateSampleFunction(), LookupFunctionLanguage.Python);

        (vhdl, python).ShouldSatisfyAllConditions(
            generated => generated.vhdl.SourceCode.ShouldStartWith("-- VHDL lookup functions generated by LogicFriday1"),
            generated => generated.python.SourceCode.ShouldStartWith("# Python lookup functions generated by LogicFriday1"));
    }

    private static LogicFunction CreateSampleFunction()
    {
        return new TruthTableLogicFunction(
            ["A", "B"],
            ["F", "G"],
            [
                ["0", "0"],
                ["1", "0"],
                ["X", "1"],
                ["1", "1"]
            ],
            "F = B; G = A;");
    }
}
